# Generated by Django 3.0.3 on 2020-08-17 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_quiz_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
